version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'database'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'